import assert from "node:assert/strict";
import test from "node:test";

import {
  QWEN35_VISION_CPU_ORACLE_REFERENCE,
  applyVision2dRotary,
  decodeBfloat16,
  visionInterpolatedPositionEmbedding,
  visionGeluPytorchTanh,
  visionGeluExact,
  visionLayerNorm,
  visionLinearBf16,
  visionMerger,
  visionNonCausalAttention,
  visionTemporalConv3dPatchEmbed,
  visionTransformerLayer,
} from "../dev/reference/qwen35-vision-cpu-oracle.js";

function close(actual: readonly number[], expected: readonly number[], tolerance = 1e-6): void {
  assert.equal(actual.length, expected.length);
  for (let index = 0; index < expected.length; index += 1) {
    if (Number.isNaN(expected[index]!)) {
      assert.ok(Number.isNaN(actual[index]!));
      continue;
    }
    assert.ok(Math.abs(actual[index]! - expected[index]!) <= tolerance, `value ${index}: ${actual[index]} !== ${expected[index]}`);
  }
}

function closePyTorch(actual: readonly number[], expected: readonly number[]): void {
  const { absoluteTolerance, relativeTolerance } =
    QWEN35_VISION_CPU_ORACLE_REFERENCE.pytorchFixtureTolerance;
  assert.equal(actual.length, expected.length);
  for (let index = 0; index < expected.length; index += 1) {
    const allowed = absoluteTolerance + relativeTolerance * Math.abs(expected[index]!);
    assert.ok(
      Math.abs(actual[index]! - expected[index]!) <= allowed,
      `value ${index}: ${actual[index]} !== ${expected[index]}`,
    );
  }
}

test("documents the pinned Transformers and PyTorch semantics used by the development oracle", () => {
  assert.deepEqual(QWEN35_VISION_CPU_ORACLE_REFERENCE, {
    transformersRevision: "3717b9cda226af7377da1944f395af0eac6e2b51",
    pytorchVersion: "2.8.0",
    pytorchDevice: "cpu",
    pytorchDtype: "float32",
    arithmetic: {
      bf16Decode: "upper-16-bits-to-f32",
      linearReduction: "sequential-f32-multiply-add",
      layerNormReduction: "origin-shifted-two-pass-f32",
      ropeFrequency: "pytorch-f32-inverse-frequency",
    },
    pytorchFixtureTolerance: {
      absoluteTolerance: 0.0005,
      relativeTolerance: 0.0000001,
    },
  });
});

test("decodes BF16 and evaluates a two-slice Conv3D patch projection before one bias", () => {
  close(Array.from(decodeBfloat16(new Uint16Array([0x3f80, 0xc020, 0x7fc0]))), [1, -2.5, Number.NaN], 0);
  close(Array.from(visionTemporalConv3dPatchEmbed({
    temporalSlices: [new Float32Array([1, 2]), new Float32Array([3, 4])],
    temporalWeights: [
      new Float32Array([1, 10, 2, 20]),
      new Float32Array([3, 30, 4, 40]),
    ],
    bias: new Float32Array([100, 200]),
    inputChannels: 1,
    patchHeight: 1,
    patchWidth: 2,
    outputWidth: 2,
  })), [250, 414]);

  assert.throws(() => visionTemporalConv3dPatchEmbed({
    temporalSlices: [new Float32Array(2), new Float32Array(2)],
    temporalWeights: [new Float32Array(4), new Float32Array(4)],
    bias: new Float32Array(2),
    inputChannels: 1,
    patchHeight: 2,
    patchWidth: 2,
    outputWidth: 2,
  }), /Conv3D.*shape/i);
});

test("stays within the pinned PyTorch envelope at the production hidden width", () => {
  const inputWidth = 1_024;
  const outputWidth = 8;
  const values = Float32Array.from(
    { length: inputWidth },
    (_, index) => Math.fround(Math.sin(index * 0.13) * 3),
  );
  const weight = Uint16Array.from(
    { length: inputWidth * outputWidth },
    (_, index) => 0x3c00 + ((index * 37) % 0x600),
  );
  const actual = visionLinearBf16({
    input: values,
    tokenCount: 1,
    inputWidth,
    outputWidth,
    weight,
    bias: Float32Array.from({ length: outputWidth }, (_, index) => Math.fround(index * 0.1)),
  });

  // Generated by PyTorch 2.8.0 CPU F.linear from the deterministic inputs above.
  closePyTorch(Array.from(actual), [
    -722.221923828125,
    62.914031982421875,
    929.163818359375,
    -721.9219360351562,
    63.214019775390625,
    929.4637451171875,
    -721.6219482421875,
    63.5140380859375,
  ]);
});

test("uses stable LayerNorm reduction at the production hidden width", () => {
  const hiddenSize = 1_024;
  const actual = visionLayerNorm({
    input: Float32Array.from(
      { length: hiddenSize },
      (_, index) => Math.fround(1_000 + Math.sin(index * 0.17) * 1.5),
    ),
    tokenCount: 1,
    hiddenSize,
    weight: new Float32Array(hiddenSize).fill(1),
    bias: new Float32Array(hiddenSize),
  });
  const indexes = [0, 1, 2, 127, 511, 512, 1_022, 1_023];
  close(indexes.map((index) => actual[index]!), [
    -0.011004914529621601,
    0.22856803238391876,
    0.4612269103527069,
    0.5418912172317505,
    -1.2694830894470215,
    -1.1415150165557861,
    -1.1647924184799194,
    -1.2870564460754395,
  ], 1e-5);
});

test("matches nonzero-frequency long-position 2D RoPE lanes", () => {
  const dimension = 64;
  const rotated = applyVision2dRotary({
    query: Float32Array.from({ length: dimension }, (_, index) => index + 1),
    key: Float32Array.from({ length: dimension }, (_, index) => dimension - index),
    tokenCount: 1,
    headCount: 1,
    headDimension: dimension,
    positions: new Int32Array([1_023, 2_047]),
    theta: 10_000,
  });
  const indexes = [0, 1, 15, 16, 17, 31, 32, 33, 47, 48, 49, 63];
  close(indexes.map((index) => rotated.query[index]!), [
    30.644084930419922, 10.227490425109863, 7.051997184753418,
    51.692806243896484, -43.04608917236328, 7.117427825927734,
    12.285764694213867, -32.48689651489258, 50.10258865356445,
    -4.225379943847656, 31.161420822143555, 71.1993179321289,
  ], 1e-5);
  close(indexes.map((index) => rotated.key[index]!), [
    54.9318962097168, -47.84853744506836, 45.115848541259766,
    27.479440689086914, -1.3759937286376953, 30.481658935546875,
    -45.852882385253906, -51.385963439941406, 25.584369659423828,
    -42.48387908935547, 49.31639099121094, 12.683394432067871,
  ], 1e-5);
});

test("keeps non-causal attention isolated between packed image segments", () => {
  close(Array.from(visionNonCausalAttention({
    query: new Float32Array([1, 0, 1, 0, 1, 0, 1, 0]),
    key: new Float32Array([1, 0, 0, 1, 100, 0, 0, 100]),
    value: new Float32Array([1, 2, 3, 4, 100, 200, 300, 400]),
    tokenCount: 4,
    headCount: 1,
    headDimension: 2,
    segmentLengths: [2, 2],
  })), [
    1.6604769229888916, 2.6604769229888916,
    1.6604769229888916, 2.6604769229888916,
    100, 200, 100, 200,
  ], 1e-5);
});

test("rejects attention workloads beyond the development-oracle bound before allocation", () => {
  assert.throws(() => visionNonCausalAttention({
    query: new Float32Array(1),
    key: new Float32Array(1),
    value: new Float32Array(1),
    tokenCount: 4_097,
    headCount: 1,
    headDimension: 1,
    segmentLengths: [4_097],
  }), /work bound/i);
});

test("uses align-corners learned positions in spatial merge-block order", () => {
  const table = new Float32Array([
    0, 10,
    100, 110,
    200, 210,
    300, 310,
  ]);
  const embedded = visionInterpolatedPositionEmbedding({
    table,
    tableHeight: 2,
    tableWidth: 2,
    hiddenSize: 2,
    gridHeight: 2,
    gridWidth: 2,
    mergeSize: 2,
  });
  close(Array.from(embedded), Array.from(table));

  // This reduced public fixture is torch.nn.functional.interpolate(..., align_corners=True),
  // then Qwen's 2x2 block-major index order.
  close(Array.from(visionInterpolatedPositionEmbedding({
    table: new Float32Array([0, 10, 100, 110]),
    tableHeight: 2,
    tableWidth: 2,
    hiddenSize: 1,
    gridHeight: 4,
    gridWidth: 4,
    mergeSize: 2,
  })), [
    0, 3.3333333, 33.3333333, 36.6666667,
    6.6666667, 10, 40, 43.3333333,
    66.6666667, 70, 100, 103.3333333,
    73.3333333, 76.6666667, 106.6666667, 110,
  ], 1e-5);
});

test("preserves every patch and channel lane through the merger shuffle", () => {
  const width = 12;
  const identity = new Uint16Array(width * width);
  for (let lane = 0; lane < width; lane += 1) identity[lane * width + lane] = 0x3f80;
  close(Array.from(visionMerger({
    input: new Float32Array([
      0, 1, 4,
      2, 7, 3,
      9, 1, 5,
      4, 6, 12,
    ]),
    patchCount: 4,
    hiddenSize: 3,
    mergeSize: 2,
    normalizationWeight: new Float32Array([1, 1, 1]),
    normalizationBias: new Float32Array(3),
    inputWeight: identity,
    inputBias: new Float32Array(width),
    intermediateSize: width,
    outputWeight: identity,
    outputBias: new Float32Array(width),
    outputSize: width,
  })), [
    -0.16022665798664093, -0.13627846539020538, 1.2562536001205444,
    -0.1641198843717575, 1.2742189168930054, -0.1489248424768448,
    1.0896116495132446, -0.13513316214084625, 0,
    -0.16022668778896332, -0.13627846539020538, 1.256253957748413,
  ], 1e-5);
});

test("matches reduced deterministic PyTorch fixtures for norm, BF16 linear, RoPE, attention, residual layer, and merger", () => {
  close(Array.from(visionLayerNorm({
    input: new Float32Array([1, 3, 2, 4]),
    tokenCount: 2,
    hiddenSize: 2,
    weight: new Float32Array([1, 1]),
    bias: new Float32Array([0, 0]),
    epsilon: 1e-6,
  })), [-0.9999995, 0.9999995, -0.9999995, 0.9999995], 1e-6);

  close(Array.from(visionLinearBf16({
    input: new Float32Array([1, 2]),
    tokenCount: 1,
    inputWidth: 2,
    outputWidth: 2,
    weight: new Uint16Array([0x3f80, 0x4000, 0x4040, 0x4080]),
    bias: new Float32Array([0.5, -0.5]),
  })), [5.5, 10.5]);

  const q = new Float32Array([1, 2, 3, 4]);
  const k = new Float32Array([4, 3, 2, 1]);
  const rotated = applyVision2dRotary({
    query: q,
    key: k,
    tokenCount: 1,
    headCount: 1,
    headDimension: 4,
    positions: new Int32Array([1, 2]),
    theta: 10_000,
  });
  close(Array.from(rotated.query), [-1.9841106, -4.4694834, 2.4623778, 0.1540075], 1e-5);
  close(Array.from(rotated.key), [0.4782673, -2.1577380, 4.4464884, 2.3117454], 1e-5);

  close(Array.from(visionNonCausalAttention({
    query: new Float32Array([1, 0, 0, 1]),
    key: new Float32Array([1, 0, 0, 1]),
    value: new Float32Array([1, 2, 3, 4]),
    tokenCount: 2,
    headCount: 1,
    headDimension: 2,
    segmentLengths: [2],
  })), [1.6604769, 2.6604769, 2.3395231, 3.3395231], 1e-5);

  close(Array.from(visionGeluPytorchTanh(new Float32Array([-1, 0, 1]))), [
    -0.1588080, 0, 0.8411920,
  ], 1e-5);
  close(Array.from(visionGeluExact(new Float32Array([-3, -1, 0, 1, 3]))), [
    -0.0040497, -0.1586553, 0, 0.8413447, 2.9959502,
  ], 1e-5);

  const qkvWeight = new Uint16Array(4 * 12);
  for (let channel = 0; channel < 4; channel += 1) {
    qkvWeight[channel * 4 + channel] = 0x3f80;
    qkvWeight[(4 + channel) * 4 + channel] = 0x3f80;
    qkvWeight[(8 + channel) * 4 + channel] = 0x3f80;
  }
  const identityFour = new Uint16Array(16);
  for (let channel = 0; channel < 4; channel += 1) identityFour[channel * 4 + channel] = 0x3f80;
  const layer = visionTransformerLayer({
    // Different normalized rows make a token-major QKV split observable.
    input: new Float32Array([1, 2, 3, 4, 1, 3, 7, 15]),
    tokenCount: 2,
    hiddenSize: 4,
    headCount: 1,
    qkvWeight,
    qkvBias: new Float32Array(12),
    attentionOutputWeight: identityFour,
    attentionOutputBias: new Float32Array(4),
    preAttentionWeight: new Float32Array([1, 1, 1, 1]),
    preAttentionBias: new Float32Array(4),
    preMlpWeight: new Float32Array([1, 1, 1, 1]),
    preMlpBias: new Float32Array(4),
    mlpUpWeight: new Uint16Array(16),
    mlpUpBias: new Float32Array(4),
    mlpDownWeight: new Uint16Array(16),
    mlpDownBias: new Float32Array(4),
    feedForwardSize: 4,
    epsilon: 1e-6,
    positions: new Int32Array([0, 0, 0, 1]),
    segmentLengths: [2],
  });
  close(Array.from(layer), [
    -0.2373714, 1.4849409, 3.3303757, 5.4220552,
    -0.1300241, 2.4150922, 7.2100883, 16.5048447,
  ], 1e-5);

  close(Array.from(visionMerger({
    input: new Float32Array([1, 3, 2, 4, 5, 7, 6, 8]),
    patchCount: 4,
    hiddenSize: 2,
    mergeSize: 2,
    normalizationWeight: new Float32Array([1, 1]),
    normalizationBias: new Float32Array(2),
    epsilon: 1e-6,
    inputWeight: new Uint16Array([
      0x3f80, 0x0000, 0x0000, 0x0000,
      0x0000, 0x0000, 0x0000, 0x0000,
      0x0000, 0x0000, 0x0000, 0x0000,
      0x0000, 0x0000, 0x0000, 0x3f80,
    ]),
    inputBias: new Float32Array(2),
    intermediateSize: 2,
    outputWeight: new Uint16Array([0x3f80, 0x0000, 0x0000, 0x3f80]),
    outputBias: new Float32Array(2),
    outputSize: 2,
  })), [-0.1586555, 0.8413445], 1e-5);
});

test("rejects non-finite values and incompatible tensor shapes", () => {
  assert.throws(() => visionLayerNorm({
    input: new Float32Array([Number.NaN]), tokenCount: 1, hiddenSize: 1,
    weight: new Float32Array([1]), bias: new Float32Array([0]), epsilon: 1e-6,
  }), /finite/i);
  assert.throws(() => visionNonCausalAttention({
    query: new Float32Array(4), key: new Float32Array(4), value: new Float32Array(4),
    tokenCount: 2, headCount: 1, headDimension: 2, segmentLengths: [1],
  }), /segment/i);
});
